module.exports = [
  { typeId: 33400, name: 'Bastion Module I', category: 'Module' },
  { typeId: 28665, name: 'Vargur', category: 'Marauder' },
  { typeId: 28661, name: 'Kronos', category: 'Marauder' },
  { typeId: 28710, name: 'Golem', category: 'Marauder' },
  { typeId: 28659, name: 'Paladin', category: 'Marauder' },
  { typeId: 17841, name: 'Federation Navy Comet', category: 'Frigate' },
  { typeId: 17703, name: 'Imperial Navy Slicer', category: 'Frigate' },
  { typeId: 17709, name: 'Omen Navy Issue', category: 'Cruiser' },
  { typeId: 17634, name: 'Caracal Navy Issue', category: 'Cruiser' },
  { typeId: 33818, name: 'Orthrus', category: 'Cruiser' },
  { typeId: 17715, name: 'Gila', category: 'Cruiser' },
  { typeId: 17720, name: 'Cynabal', category: 'Cruiser' },
  { typeId: 17738, name: 'Machariel', category: 'Battleship' },
  { typeId: 17736, name: 'Nightmare', category: 'Battleship' },
  { typeId: 17920, name: 'Bhaalgorn', category: 'Battleship' },
  { typeId: 17740, name: 'Vindicator', category: 'Battleship' },
  { typeId: 17918, name: 'Rattlesnake', category: 'Battleship' },
  { typeId: 33472, name: 'Nestor', category: 'Battleship' },
  { typeId: 22428, name: 'Redeemer', category: 'Battleship' },
  { typeId: 42210, name: 'High-grade Asklepian Alpha', category: 'Implant' },
  { typeId: 42215, name: 'High-grade Asklepian Omega', category: 'Implant' },
  { typeId: 20499, name: 'High-grade Amulet Alpha', category: 'Implant' },
  { typeId: 20509, name: 'High-grade Amulet Omega', category: 'Implant' },
  { typeId: 15681, name: 'Caldari Navy Ballistic Control System', category: 'Module' },
  { typeId: 15806, name: 'Republic Fleet Gyrostabilizer', category: 'Module' },
  { typeId: 13943, name: 'True Sansha Heat Sink', category: 'Module' },
  { typeId: 23105, name: 'Imperial Navy Multifrequency L', category: 'Ammo' },
  { typeId: 27142, name: "Zainou 'Gypsy' CPU Management EE-605", category: 'Implant' }
];
